### ISSUE TITLE
Extend --remove_solution_code to include autograder tests

### ISSUE THREAD

**Issue by adowling2** [jckantor/nbpages#20]
Mimic the syntax of Vocareum.

**Comment by adowling2** [comment]
Here is the documentation: https://help.vocareum.com/en/articles/3658959-grading-with-jupyter-notebook

We need to strip out cells that are marked as ``Autograder test`` with nbgrader. We should have lint search for ``### BEGIN HIDDEN TESTS`` and ``### END HIDDEN TESTS`` in all code cells not marked as ``Autograder test`` by nbgrader. Sometimes I forget to mark the cells.

**Comment by adowling2** [comment]
@jckantor I just ran `nbpages --remove_solution_code` and got this output:

```
- remove solution code from 01.01-Jupyter-Notebooks.ipynb
- remove hidden tests code from 01.01-Jupyter-Notebooks.ipynb
- remove hidden tests code from 01.01-Jupyter-Notebooks.ipynb
```

Why is it double printing?

**Comment by adowling2** [comment]
The trick was running `nbpages --remove_solution_code --publish`.

**Comment by jckantor** [comment]
A message is printed for every cell that is removed. If there is more than one hidden test then there are multiple messages. Will change this for a more informative message.

**Comment by jckantor** [comment]
This feature has been renamed --remove_code, and implemented in a more generic and testable method. Documentatiion has been added to the readme file.  Going to close this one out.
