### ISSUE TITLE
Create /data and /figures folders with setup.

### ISSUE THREAD

**Issue by adowling2** [jckantor/nbpages#22]
This means it will work the same for /notebooks and /docs.

How to handle the case with two repos? It would need to copy only the files that are used.

**Comment by adowling2** [comment]
Only do this if the folders do not exist.

**Comment by adowling2** [comment]
It is easy to find the figures. Is there an easy way to find all possible data files? Restrict to only `.txt` and `.csv` for now?

**Comment by adowling2** [comment]
We need to leave out comments when we parse through the code.

**Comment by adowling2** [comment]
Is there a simple regular expression to ignore comments in Python code?

**Comment by adowling2** [comment]
Important order is strip then search.

**Comment by adowling2** [comment]
This would also require extending the destination to a higher-level folder. Or tell the user to always run in the destination repo. You can still keep `dst` as a useful option.

**Comment by adowling2** [comment]
Change `--src` to `-src_repo`.

**Comment by adowling2** [comment]
Remove `dst` and `src` options. Make these and `/data` and `/figure` part of `nbpages.cfg`.

**Comment by adowling2** [comment]
We discussed/agreed on putting `/data` and `/figure` in the top directory.

**Comment by jckantor** [comment]
removed dst and src command line options, now configurable in nbpages.cfg. /figures and /data now created by setup (in not present), alternative directory names can be set in nbpages.cfg
