### ISSUE TITLE
Links to notebooks in repos owned by an org do not work

### ISSUE THREAD

**Issue by adowling2** [jckantor/nbpages#26]
For example, see the links to notebooks here: https://ndcbe.github.io/cbe67701-uncertainty-quantification/

This may be related to issue #13.

**Comment by adowling2** [comment]
Here is an example link:

https://ndcbe.github.io/cbe67701-uncertainty-quantification/ndcbe.github.io/cbe67701-uncertainty-quantification/03.00-Input-Parameter-Distributions.html

You can see there is an extra `ndcbe.github.io/cbe67701-uncertainty-quantification/`.

Here is the current `nbpages.cfg`:
```
[NBPAGES]
github_repo_url = git@github.com:ndcbe/cbe67701-uncertainty-quantification.git
github_user_name = git@github.com:ndcbe
github_repo_name = cbe67701-uncertainty-quantification
github_pages_url = ndcbe.github.io/cbe67701-uncertainty-quantification
repository = git@github.com:ndcbe/cbe67701-uncertainty-quantification
page_title = cbe67701-uncertainty-quantification
page_url = https://git@github.com:ndcbe.github.io/cbe67701-uncertainty-quantification
```

**Comment by jckantor** [comment]
working now.
