### ISSUE TITLE
Lint extension: verify the appreance of data and figures in a notebook

### ISSUE THREAD

**Issue by adowling2** [jckantor/nbpages#30]
This helps find "orphaned" data and figures. It is also a precursor to data and figure TOC.

**Comment by jckantor** [comment]
Here's how this might work ...

* complete section numbering
* reads a list of files appearing in data_dir
* for each file name, search over all cells in all sections in all notebooks to create an index with the section number and link to section where the string appears. The section is the most specific level link available.
* sort data file index by section and by file name, then report by filename.
* repeat for figures.

Report
* data file index
* figure file index
* add list of data to table of contents for each notebook.

**Comment by adowling2** [comment]
I like it! Your approach makes sense.

**Comment by jckantor** [comment]
This has been implemented for figures. The result is a Figure Index that appears in the index.md home page.  It's been incredibly useful for finding and managing figures, and also enabled selective copying of figures for --publish.  Need to finish this with an implementation for data files.

**Comment by jckantor** [comment]
This is now done for both figures and data files.  Only files actually appearing in the notebooks get copied to docs. Lint reports unused files.  The index page provides links to a data and figure index, if they are non-nil.
