### ISSUE TITLE
Implement "easier"/"poor man's" testing

### ISSUE THREAD

**Issue by adowling2** [jckantor/nbpages#31]
Create three repositories owned by ndcbe:

1. `nbpages-testing` (completely hosted in 1 repo) 
2. `nbpages-testing-dev` (private, publishes to `nbpages-testing-public`)
2. `nbpages-testing-public` (public)

The repos would contain just a few example notebooks and a script to completely reset `/docs`.

**Comment by jckantor** [comment]
The repos are set up and publishing from the private to the public repo has been verified.  Still need to add a feature to clear out docs directory.

**Comment by jckantor** [comment]
The code now maintains a clean destination directory by removing old data, figures, html, notebooks before writing.  This reduces the chance that old notebooks might be inadvertently left behind.  Needs testing, but that's a different issue.
