### ISSUE TITLE
can nbpages.cfg be hard coded?

### ISSUE THREAD

**Issue by jckantor** [jckantor/nbpages#35]
Can we hard code the name 'nbpages.cfg'?  Currently there is a --config option to allow the possibility of an alternate or multiple config file.  But would that ever be necessary?  For the case of multiple destinations, nbpages could always be run from the destination directory with a unique nbpages.cfg.

**Comment by adowling2** [comment]
Using the design that nbpages is always run from the destination directory, I think it is fine to hardcode ``nbpages.cfg``.

**Comment by jckantor** [comment]
Yes, I agree. Going to leave this alone and close it out.
