### ISSUE TITLE
Chapter numbers missing, error in nbpages.cfg, TOC links broken

### ISSUE THREAD

**Issue by adowling2** [jckantor/nbpages#44]
https://ndcbe.github.io/cbe67701-uncertainty-quantification/

**Comment by adowling2** [comment]
Links are also broken.

**Comment by adowling2** [comment]
Here is the link for a notebook in the current website:
https://git@github.com:ndcbe.github.io/cbe67701-uncertainty-quantification/11.00-Predictive-Models-Informed-by-Simulation-Measurement-and-Surrogates.html

The link should be
https://ndcbe.github.io/cbe67701-uncertainty-quantification/11.00-Predictive-Models-Informed-by-Simulation-Measurement-and-Surrogates.html

**Comment by adowling2** [comment]
Need an extra split to construct github_user_name. A possibility is the @adowling2 checked out with ssh but @jckantor checked out with https for testing.

**Comment by adowling2** [comment]
Version from ``nbpages --setup``:
https://github.com/ndcbe/cbe67701-uncertainty-quantification/blob/6c743e260364f5d9ca33929e47e1385175eebfd2/nbpages.cfg

Corrected version:
https://github.com/ndcbe/cbe67701-uncertainty-quantification/blob/b50ac7d9d33b8aeb8eb105e2fd778fcd77c7a015/nbpages.cfg

**Comment by adowling2** [comment]
Need to parse username first on `:` to remove the protocol than `/` to get the username. We confirmed that @jckantor checked out with https but @adowling2 checked out with ssh.

**Comment by adowling2** [comment]
Note to self: need to check links on the table on contents too. There might still be a bug.

**Comment by adowling2** [comment]
I just reran with the development version of nbpages. I still think there is a mistake:
https://github.com/ndcbe/cbe67701-uncertainty-quantification/blob/159c50c0eeb00d1f176e737bce558b05e0a5a3e3/nbpages.cfg

@jckantor

**Comment by adowling2** [comment]
@jckantor I actually switched to the development branch but forgot to pull. I just pulled to the most recent version. It appears to work. Waiting for the github pages to update.

**Comment by jckantor** [comment]
I think this is working now. So close this .. reopen if there's a problem.
