### ISSUE TITLE
Duplicate entries in data index

### ISSUE THREAD

**Issue by adowling2** [jckantor/nbpages#48]
https://ndcbe.github.io/cbe67701-uncertainty-quantification/data_index.html

This is because I both give the name of the text file markdown description and I use it in the code. This is a low priority.

**Comment by adowling2** [comment]
I now add subsections, so there is no longer a duplicate in this example. But it is still easy to make a duplicate.

**Comment by jckantor** [comment]
The data and figure indices are now dedup'd upon construction.
